import { useState, useRef, useEffect } from 'react';
import { gsap } from 'gsap';
import { ShieldCheck, Sparkles, BookOpen, Users, ArrowRight } from 'lucide-react';

const CONSENT_ITEMS = [
  {
    icon: Sparkles,
    title: 'AI Study Assistant',
    text: 'This chat uses AI to help you with homework, studying, and learning. It is not a human — responses are generated by AI and may not always be accurate.',
  },
  {
    icon: BookOpen,
    title: 'Your Learning Companion',
    text: 'Ask questions about any subject, get help with assignments, or just explore ideas. 60 Watts of Intelligence is here to support your learning journey.',
  },
  {
    icon: Users,
    title: 'Safety Monitoring',
    text: 'This chat is monitored by a professional safety team to ensure your wellbeing. If you are ever in distress, trained professionals are here to help.',
  },
  {
    icon: ShieldCheck,
    title: 'Privacy & Security',
    text: 'Your messages are encrypted and private. Type @socialworker at any time if you need to talk to someone about how you are feeling.',
  },
];

export default function ConsentGate({ onConsent }) {
  const [acknowledged, setAcknowledged] = useState(false);
  const containerRef = useRef(null);
  const cardsRef = useRef([]);
  const ctaRef = useRef(null);

  useEffect(() => {
    if (!containerRef.current) return;

    gsap.fromTo(
      containerRef.current,
      { opacity: 0, y: 20 },
      { opacity: 1, y: 0, duration: 0.6, ease: 'power3.out' }
    );

    gsap.fromTo(
      cardsRef.current.filter(Boolean),
      { opacity: 0, y: 16 },
      { opacity: 1, y: 0, duration: 0.4, stagger: 0.12, delay: 0.3, ease: 'power2.out' }
    );
  }, []);

  useEffect(() => {
    if (!ctaRef.current) return;
    if (acknowledged) {
      gsap.fromTo(
        ctaRef.current,
        { opacity: 0, y: 8 },
        { opacity: 1, y: 0, duration: 0.3, ease: 'power2.out' }
      );
    }
  }, [acknowledged]);

  return (
    <div className="min-h-screen bg-ember-base flex items-center justify-center p-4">
      <div ref={containerRef} className="w-full max-w-lg">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="w-16 h-16 rounded-2xl ember-gradient mx-auto mb-4 flex items-center justify-center shadow-lg">
            <Sparkles className="w-8 h-8 text-ember-text" />
          </div>
          <h1 className="font-heading text-3xl text-ember-text mb-2">
            60 Watts of Intelligence
          </h1>
          <p className="text-ember-muted text-sm max-w-sm mx-auto leading-relaxed">
            Your AI-powered study companion. Let's learn something new today.
          </p>
        </div>

        {/* Consent cards */}
        <div className="space-y-3 mb-6">
          {CONSENT_ITEMS.map((item, i) => {
            const Icon = item.icon;
            return (
              <div
                key={i}
                ref={(el) => (cardsRef.current[i] = el)}
                className="frost-panel rounded-xl px-4 py-4 flex gap-4 items-start"
              >
                <div className="w-9 h-9 rounded-lg bg-ember-primary/10 flex items-center justify-center flex-shrink-0 mt-0.5">
                  <Icon className="w-4 h-4 text-ember-primary" />
                </div>
                <div>
                  <h3 className="text-ember-text text-sm font-medium mb-1">{item.title}</h3>
                  <p className="text-ember-muted text-xs leading-relaxed">{item.text}</p>
                </div>
              </div>
            );
          })}
        </div>

        {/* Acknowledge checkbox */}
        <label className="flex items-start gap-3 cursor-pointer frost-panel rounded-xl px-4 py-4 mb-4">
          <input
            type="checkbox"
            checked={acknowledged}
            onChange={(e) => setAcknowledged(e.target.checked)}
            className="mt-0.5 w-4 h-4 rounded border-ember-muted accent-ember-primary flex-shrink-0"
          />
          <span className="text-ember-text text-xs leading-relaxed">
            I understand this chat is AI-powered and monitored for safety. I consent to professional intervention if a safety concern is detected.
          </span>
        </label>

        {/* CTA */}
        {acknowledged && (
          <button
            ref={ctaRef}
            onClick={onConsent}
            className="w-full ember-gradient rounded-xl px-6 py-3.5 text-ember-text font-medium flex items-center justify-center gap-2 ember-glow transition-all hover:scale-[1.01] active:scale-[0.99]"
          >
            Start Learning
            <ArrowRight className="w-4 h-4" />
          </button>
        )}

        {/* Footer */}
        <p className="text-center text-ember-muted/50 text-[10px] font-mono mt-6">
          Protected by Social Worker AI &middot; 60 Watts of Clarity &middot; If in immediate danger, call 988 or 911
        </p>
      </div>
    </div>
  );
}
